version: '3.8'

services:
  property-verifier:
    build: .
    ports:
      - "8000:8000"  # FastAPI backend
      - "8501:8501"  # Streamlit frontend
    volumes:
      - ./uploads:/app/uploads
      - ./app:/app/app
      - ./frontend:/app/frontend
    environment:
      - PYTHONPATH=/app
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    command: ["serve"]

volumes:
  ollama_data:
